// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQcSXxaZm9YkbdluVD_BQ5lhXh8RSSiCg',
    appId: '1:192434701878:web:47467f37c0a0adf6a6ba97',
    messagingSenderId: '192434701878',
    projectId: 'chatgpt-clone-fcfa9',
    authDomain: 'chatgpt-clone-fcfa9.firebaseapp.com',
    storageBucket: 'chatgpt-clone-fcfa9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiFhqYM-LUrvSeMcyKTBFl6A1-aVjcfZk',
    appId: '1:192434701878:android:e432146f82311a32a6ba97',
    messagingSenderId: '192434701878',
    projectId: 'chatgpt-clone-fcfa9',
    storageBucket: 'chatgpt-clone-fcfa9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsFGOp5tdcNBmrde9fGErNx5mdsP2vOfQ',
    appId: '1:192434701878:ios:8d5b49f6a91c70c7a6ba97',
    messagingSenderId: '192434701878',
    projectId: 'chatgpt-clone-fcfa9',
    storageBucket: 'chatgpt-clone-fcfa9.appspot.com',
    iosBundleId: 'com.example.mobile',
  );
}
