// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW1BqK8oZYEDoPv9xyyuaEN0XguvyX_A4',
    appId: '1:522575518781:web:b9b3f142abfcbaf70a9e54',
    messagingSenderId: '522575518781',
    projectId: 'chatgpt-clone-a2f41',
    authDomain: 'chatgpt-clone-a2f41.firebaseapp.com',
    storageBucket: 'chatgpt-clone-a2f41.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCYr3ThRH2ekiyXkpy8aHB6qFfOTg69Gs',
    appId: '1:522575518781:android:ce02e6ba472ac8bc0a9e54',
    messagingSenderId: '522575518781',
    projectId: 'chatgpt-clone-a2f41',
    storageBucket: 'chatgpt-clone-a2f41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnOzkHOH93hrMQBEiOmR6_rUSx0aWby5A',
    appId: '1:522575518781:ios:c3d20a791f546b5a0a9e54',
    messagingSenderId: '522575518781',
    projectId: 'chatgpt-clone-a2f41',
    storageBucket: 'chatgpt-clone-a2f41.appspot.com',
    iosBundleId: 'com.example.mobile',
  );
}
